### PR TITLE
Fix multiple build issues

### PR DESCRIPTION
**Pull request by glaubitz**
This PR contains multiple changes that were required to make the package build in a current Debian unstable chroot. Tested with qemu-m68k-user.

### CODE REVIEW

**Review by vivier — COMMENTED** [review]
We are in the case when we are not on a m68k machine and we don't have a cross-compiler, so this is an error case, we really must exit.

**Review by vivier — APPROVED** [review]

**Review by vivier — APPROVED** [review]

**Review by vivier — APPROVED** [review]

**Review by vivier — CHANGES_REQUESTED** [review]
I think it's better to remove the constant NULL comparison.

**Review by vivier — CHANGES_REQUESTED** [review]
Just removing the "inline" from the console.h is enough.

**Review by vivier — COMMENTED** [review]
I think you should also remove clean and dist targets as they are imported now from Rules.mk

**Review by vivier — COMMENTED** [review]
tools are supposed to be built and installed on another arch than m68k. Did you test your change in a cross-build environment?

**Comment by glaubitz** [comment]
On 03/16/2017 09:01 AM, Laurent Vivier wrote:
> Just removing the "inline" from the console.h is enough.

I discussed this with @karcherm and he said, the original reasoning of the inlining was to accelerate console_putstring() which it would still do with my current change. For external translation units, the function would be exported normally.

**Comment by glaubitz** [comment]
> We are in the case when we are not on a m68k machine and we don't have a cross-compiler, so this is an error case, we really must exit.

I agree. However, the problem is that the machine detection is not bullet-proof and may fail, so we will just end up with a half-generated tools.mk which was the original reason we had problems building the documentation.

**Comment by glaubitz** [comment]
> I think it's better to remove the constant NULL comparison.

Can we be 100% sure that the pointer passed is never NULL?

**Comment by glaubitz** [comment]
> tools are supposed to be built and installed on another arch than m68k. Did you test your change in a cross-build environment?

Do you mean the changes regarding ```make install``` in particular?

The problem here is that the binaries are built into $(TARGET), but ```make install``` as it is currently used here does not support that.

**Review by vivier — APPROVED** [review]

**Pull request merged**
